export const BASE_URLS = {
  BASE_URL_WORKFLOW_EXECUTION: import.meta.env.VITE_BASE_URL_WORKFLOW_EXECUTION,
  BASE_URL_WORKFLOW_GENERATOR: import.meta.env.VITE_BASE_URL_WORKFLOW_GENERATOR,
  BASE_URL_TOOLS_REGISTRY: import.meta.env.VITE_BASE_URL_TOOLS_REGISTRY,
  BASE_URL_CONFIGURATION: import.meta.env.VITE_BASE_URL_CONFIGURATION,
  BASE_URL_PROJECT: import.meta.env.VITE_BASE_URL_PROJECT,
  KOGITO_GRAPHQL_URL: import.meta.env.VITE_KOGITO_GRAPHQL_URL,
}
